import { useState } from "react";
import { Link, useFetcher, useLoaderData } from "react-router";
import type { ProjectRow } from "./projects-page";

type RecordRow={toolKey:string;type:string;state:string;payload:unknown};
const places:Record<string,string>={"26-055":"Tampa, Florida","26-068":"St. Petersburg, Florida","26-052":"Dade City, Florida",CMAR:"Tampa, Florida"};
const currency=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value);

export function Dashboard({confirm}:{confirm:(value:string)=>void}){
  const fetcher=useFetcher(),{projects,records}=useLoaderData<{projects:ProjectRow[];records:RecordRow[]}>(),[metric,setMetric]=useState<string>();
  const activities=[["3 bids received","Oakfield Trails · Division 09"],["Scope confirmation ready","JHACH · Electrical"],["Insurance expires soon","2 trade partners need review"],["Proposal review assigned","PHSC East Campus Repairs"]];
  const approved=new Set(records.filter(record=>record.toolKey==="activity"&&record.state==="approved").map(record=>(record.payload as {title?:string})?.title));
  const pending=activities.filter(item=>!approved.has(item[0]));
  const metrics=[["Active projects",String(projects.filter(item=>item.status==="active"||item.status==="bidding"||item.status==="pricing").length),"Open portfolio"],["Open solicitations",String(records.filter(item=>item.toolKey==="solicitations"&&item.state!=="closed").length),"Review packages"],["Proposals due",String(records.filter(item=>item.toolKey==="proposal-designer"&&item.state!=="closed").length),"Open proposals"],["Pending actions",String(pending.length),"Review actions"]];
  return <><div className="metrics">{metrics.map(item=><button className="metric metric-button" key={item[0]} onClick={()=>setMetric(item[0])}><label>{item[0]}</label><strong>{item[1]}</strong><small>{item[2]} →</small></button>)}</div><div className="content-grid"><section><div className="panel-head standalone"><h2>PRIORITY PROJECTS</h2><Link to="/app/projects" className="text-link">VIEW ALL →</Link></div><div className="cards project-cards">{projects.slice(0,4).map((project,index)=><ProjectCard project={project} index={index}/>)}</div></section><section className="panel"><div className="panel-head"><h2>ACTIVITY + ACTIONS</h2><span className="panel-caption">{pending.length} OPEN</span></div>{pending.map(item=><div className="activity-row activity-action" key={item[0]}><i/><div><b>{item[0]}</b><span>{item[1]}</span></div><div className="activity-buttons"><button className="secondary" onClick={()=>confirm(`${item[0]} · ${item[1]}`)}>VIEW</button><button className="primary" onClick={()=>fetcher.submit({intent:"activity-approve",title:item[0],detail:item[1]},{method:"post"})}>APPROVE</button></div></div>)}{!pending.length&&<div className="activity-empty"><b>YOU'RE CAUGHT UP</b><span>Approved actions are removed from this queue.</span></div>}</section></div>{metric&&<MetricDrawer title={metric} projects={projects} records={records} close={()=>setMetric(undefined)}/>}</>;
}

function ProjectCard({project,index}:{project:ProjectRow;index:number}){const detail=(project.data??{}) as Record<string,unknown>,coverage=[62,48,76,25][index%4],days=project.dueDate?Math.max(0,Math.ceil((new Date(`${project.dueDate}T12:00:00`).getTime()-Date.now())/86400000)):0;return <article className="reference-card" key={project.id}><div className="reference-top"><span className={`project-state ${project.status}`}>{project.status}</span><button aria-label={`More options for ${project.name}`}>•••</button></div><h3>{project.name}</h3><div className="project-identity"><b>{project.code}</b><span>{String(detail.location??places[project.code]??"Location not set")}</span></div><div className="bid-signal"><div><label>{project.status==="bidding"?"BID COVERAGE":"NEXT DEADLINE"}</label><strong>{project.status==="bidding"?`${coverage}%`:`${days} DAYS`}</strong></div><div className="coverage-bar"><i style={{width:`${project.status==="bidding"?coverage:Math.min(100,days*3)}%`}}/></div></div><div className="reference-dates"><div><label>BID / DUE</label><b>{project.dueDate??"NOT SET"}</b></div><div><label>COMPLETION</label><b>{project.completionDate??"NOT SET"}</b></div></div><div className="reference-actions"><Link to={`/app/projects/${project.id}`}>OPEN PROJECT</Link><Link to={`/app/data?project=${project.id}`}>FILES</Link></div><footer><span>ESTIMATED VALUE</span><b>{currency(Number(detail.estimatedValue??0))}</b></footer></article>}

function MetricDrawer({title,projects,records,close}:{title:string;projects:ProjectRow[];records:RecordRow[];close:()=>void}){const tool=title.includes("Solicitation")?"solicitations":title.includes("Proposal")?"proposal-designer":undefined;const items=tool?records.filter(record=>record.toolKey===tool):[];return <div className="drawer-backdrop" onMouseDown={close}><aside className="metric-drawer" onMouseDown={event=>event.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">DASHBOARD DETAIL</span><h2>{title.toUpperCase()}</h2></div><button className="secondary" onClick={close}>CLOSE</button></div>{title==="Active projects"?projects.map(project=><Link className="drawer-link" key={project.id} to={`/app/projects/${project.id}`}><b>{project.code} · {project.name}</b><span>{project.status} · {project.owner}</span></Link>):items.length?items.map((record,index)=><div className="drawer-link" key={index}><b>{(record.payload as {title?:string})?.title??record.type}</b><span>{record.state}</span></div>):<div className="activity-empty"><b>NO ITEMS YET</b><span>Create the first item from an open project.</span></div>}<Link className="primary drawer-all" to={tool?`/app/projects`:`/app/projects`}>CONTINUE IN WORKSPACE</Link></aside></div>}
