import { useState, type ReactNode } from "react";
import { Link, NavLink, useFetcher } from "react-router";
import { modules } from "../lib/navigation";
import { ToolPage } from "./tool-page";
import type { ProjectRow } from "./projects-page";

type WorkflowRow={id:string;projectId:string|null;toolKey:string;type:string;state:string;revision:number;payload:unknown};
type BidPackage={id:string;title:string;sent:number;received:number;state:string};
const projectDefaults:Record<string,Record<string,string|number>>={"26-055":{location:"1725 Riverside Drive, Tampa, FL 33602",projectOwner:"Oakfield Development",architect:"Halstead Architecture",description:"Mixed-use residential community and amenity center",sizeSf:148500,anticipatedValue:31800000,estimatedValue:30450000,proposedValue:31125000},"26-068":{location:"600 5th Street South, St. Petersburg, FL 33701",projectOwner:"Johns Hopkins All Children's Hospital",architect:"HDR",description:"Specialty pharmacy renovation within an active healthcare campus",sizeSf:28600,anticipatedValue:12400000,estimatedValue:11980000,proposedValue:12150000},"26-052":{location:"36727 Blanton Road, Dade City, FL 33523",projectOwner:"Pasco-Hernando State College",architect:"Harvard Jolly Architecture",description:"Campus envelope, interiors, and infrastructure repairs",sizeSf:74200,anticipatedValue:8650000,estimatedValue:8420000,proposedValue:8515000},CMAR:{location:"5200 K-Bar Ranch Parkway, Tampa, FL 33647",projectOwner:"City of Tampa",architect:"Wannemacher Jensen Architects",description:"CMAR delivery for a new community park and recreation facilities",sizeSf:96500,anticipatedValue:22750000,estimatedValue:21900000,proposedValue:0}};
const samplePackages:BidPackage[]=[{id:"",title:"03 30 00 Cast-in-Place Concrete",sent:8,received:5,state:"issued"},{id:"",title:"09 29 00 Gypsum Board",sent:12,received:7,state:"issued"},{id:"",title:"26 00 00 Electrical",sent:9,received:0,state:"draft"},{id:"",title:"23 00 00 HVAC",sent:7,received:4,state:"issued"}];
const money=(value:unknown)=>typeof value==="number"&&value?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value):"Not set";

export function ProjectWorkspace({project,records,toolSlug,content}:{project:ProjectRow;records:WorkflowRow[];toolSlug?:string;content?:ReactNode}){const details={...projectDefaults[project.code],...((project.data??{}) as Record<string,unknown>)},projectRecords=records.filter(record=>record.projectId===project.id),scope=projectRecords.filter(record=>record.toolKey==="risk"),solicitations=projectRecords.filter(record=>record.toolKey==="solicitations"),proposals=projectRecords.filter(record=>record.toolKey==="proposal-designer"),packages:BidPackage[]=solicitations.length?solicitations.map((record,index)=>{const payload=record.payload as {title?:string;sent?:number;received?:number};return {id:record.id,title:payload.title??`Bid package ${index+1}`,sent:Number(payload.sent??8),received:Number(payload.received??(record.state==="issued"?3:0)),state:record.state};}):samplePackages;return <div className="project-shell"><aside className="project-tools"><div className="project-tools-title"><span>PROJECT TOOLS</span></div><NavLink end to={`/app/projects/${project.id}`}>Overview</NavLink>{modules.map(item=><NavLink key={item[0]} to={`/app/tools/${item[0]}?project=${project.id}`}>{item[2]}</NavLink>)}<div className="project-tools-divider"/><NavLink to={`/app/data?project=${project.id}&type=file`}>Files</NavLink><NavLink to={`/app/data?project=${project.id}&type=report`}>Reports</NavLink><NavLink to={`/app/data?project=${project.id}&type=template`}>Templates</NavLink></aside><section className="project-center">{content??(toolSlug?<ToolPage slug={toolSlug} confirm={()=>{}}/>:<ProjectOverview project={project} details={details} scope={scope} packages={packages} proposals={proposals}/>)}</section><ProjectInformation project={project} details={details} packages={packages}/></div>}

function ProjectOverview({project,details,scope,packages,proposals}:{project:ProjectRow;details:Record<string,unknown>;scope:WorkflowRow[];packages:BidPackage[];proposals:WorkflowRow[]}){const fetcher=useFetcher(),scopeComplete=scope.some(item=>item.state==="approved"||item.state==="closed"),recentProposal=proposals.at(-1),proposalPayload=recentProposal?.payload as {title?:string}|undefined;return <div className="project-overview"><div className="project-overview-toolbar"><Link to="/app/projects">← ALL PROJECTS</Link><div><Link to={`/app/tools/risk?project=${project.id}`}>SCOPE REVIEW</Link><Link to={`/app/tools/solicitations?project=${project.id}&create=1`}>NEW BID PACKAGE</Link></div></div><section className="project-command-center"><div className="project-pulse"><div><label>STATUS</label><strong className="status-value">{project.status}</strong><span>{project.phase}</span></div><div><label>SCOPE REVIEW</label><strong>{scopeComplete?"Complete":"Incomplete"}</strong><Link to={`/app/tools/risk?project=${project.id}`}>{scopeComplete?"OPEN REVIEW":"RESOLVE COVERAGE"}</Link></div><div><label>LATEST ESTIMATE</label><strong>{money(details.estimatedValue)}</strong><Link to={`/app/data?project=${project.id}&type=estimate`}>OPEN ESTIMATE</Link></div><div><label>LATEST OWNER PROPOSAL</label><strong>{proposalPayload?.title??"No proposal sent"}</strong><Link to={`/app/tools/proposal-designer?project=${project.id}`}>{recentProposal?"OPEN PROPOSAL":"CREATE PROPOSAL"}</Link></div></div><div className="overview-packages"><div className="overview-section-head"><div><span>BID PACKAGES</span><b>{packages.length} OPEN</b></div><Link to={`/app/tools/solicitations?project=${project.id}`}>MANAGE ALL →</Link></div>{packages.map(item=>{const covered=item.received>0,ratio=item.sent?Math.min(100,Math.round(item.received/item.sent*100)):0;return <div className={`overview-package ${covered?"covered":"uncovered"}`} key={item.id??item.title}><div><b>{item.title}</b><span>{item.received} received / {item.sent} sent</span></div><div className="coverage-bar"><i style={{width:`${ratio}%`}}/></div>{project.status==="bidding"&&<div className="overview-package-actions">{item.id?<button onClick={()=>fetcher.submit({intent:"workflow-update",id:item.id,state:"issued",title:item.title,detail:"Bid update sent"},{method:"post"})}>SEND UPDATE</button>:<Link to={`/app/tools/solicitations?project=${project.id}&create=1`}>SEND UPDATE</Link>}<Link to={`/app/tools/subcontractors?project=${project.id}&create=1`}>ADD CONTRACTOR</Link></div>}</div>})}</div></section></div>}

function ProjectInformation({project,details,packages}:{project:ProjectRow;details:Record<string,unknown>;packages:BidPackage[]}){const fetcher=useFetcher(),[editingLead,setEditingLead]=useState(false),[lead,setLead]=useState(project.owner);function saveLead(){fetcher.submit({intent:"update",id:project.id,field:"owner",value:lead},{method:"post"});setEditingLead(false);}return <aside className="project-information"><div className="project-info-head"><span>PROJECT INFORMATION</span><p>{String(details.location??"Address not set")}</p></div><dl><div><dt>Owner</dt><dd>{String(details.projectOwner??"Not set")}</dd></div><div><dt>Architect</dt><dd>{String(details.architect??"Not set")}</dd></div><div className="wide"><dt>Project lead</dt><dd>{editingLead?<span className="lead-editor"><input value={lead} onChange={event=>setLead(event.target.value)} autoFocus/><button onClick={saveLead}>SAVE</button><button onClick={()=>setEditingLead(false)}>CANCEL</button></span>:<span className="lead-value">{project.owner}<button onClick={()=>setEditingLead(true)}>EDIT</button></span>}</dd></div><div className="wide"><dt>Description</dt><dd>{String(details.description??"No description")}</dd></div><div><dt>Size</dt><dd>{details.sizeSf?`${Number(details.sizeSf).toLocaleString()} SF`:"Not set"}</dd></div><div><dt>Anticipated value</dt><dd>{money(details.anticipatedValue)}</dd></div><div><dt>Estimated value</dt><dd>{money(details.estimatedValue)}</dd></div><div><dt>Proposed value</dt><dd>{money(details.proposedValue)}</dd></div></dl><div className="project-dates"><span>PROJECT DATES</span><div><label>Start</label><b>{project.startDate??"Not set"}</b></div><div><label>Bid / due</label><b>{project.dueDate??"Not set"}</b></div><div><label>Completion</label><b>{project.completionDate??"Not set"}</b></div></div><div className="package-list"><span>COVERAGE SUMMARY</span>{packages.map(item=>{const ratio=item.sent?Math.min(100,Math.round(item.received/item.sent*100)):0;return <div className={`package-row ${item.received?"covered":"uncovered"}`} key={item.id??item.title}><b>{item.title}</b><small>{item.received} / {item.sent}</small><div className="coverage-bar"><i style={{width:`${ratio}%`}}/></div></div>})}</div></aside>}
