import { Link, NavLink } from "react-router";
import { modules } from "../lib/navigation";
import { ToolPage } from "./tool-page";
import type { ProjectRow } from "./projects-page";

type WorkflowRow={id:string;projectId:string|null;toolKey:string;type:string;state:string;revision:number;payload:unknown};
const projectDefaults:Record<string,Record<string,string|number>>={
  "26-055":{location:"1725 Riverside Drive, Tampa, FL 33602",projectOwner:"Oakfield Development",architect:"Halstead Architecture",description:"Mixed-use residential community and amenity center",sizeSf:148500,anticipatedValue:31800000,estimatedValue:30450000,proposedValue:31125000},
  "26-068":{location:"600 5th Street South, St. Petersburg, FL 33701",projectOwner:"Johns Hopkins All Children’s Hospital",architect:"HDR",description:"Specialty pharmacy renovation within an active healthcare campus",sizeSf:28600,anticipatedValue:12400000,estimatedValue:11980000,proposedValue:12150000},
  "26-052":{location:"36727 Blanton Road, Dade City, FL 33523",projectOwner:"Pasco-Hernando State College",architect:"Harvard Jolly Architecture",description:"Campus envelope, interiors, and infrastructure repairs",sizeSf:74200,anticipatedValue:8650000,estimatedValue:8420000,proposedValue:8515000},
  CMAR:{location:"5200 K-Bar Ranch Parkway, Tampa, FL 33647",projectOwner:"City of Tampa",architect:"Wannemacher Jensen Architects",description:"CMAR delivery for a new community park and recreation facilities",sizeSf:96500,anticipatedValue:22750000,estimatedValue:21900000,proposedValue:0},
};
const samplePackages=[{title:"03 30 00 Cast-in-Place Concrete",sent:8,received:5},{title:"09 29 00 Gypsum Board",sent:12,received:7},{title:"26 00 00 Electrical",sent:9,received:0},{title:"23 00 00 HVAC",sent:7,received:4}];
const money=(value:unknown)=>typeof value==="number"&&value?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(value):"Not set";

export function ProjectWorkspace({project,records,toolSlug}:{project:ProjectRow;records:WorkflowRow[];toolSlug?:string}) {
  const details={...projectDefaults[project.code],...((project.data??{}) as Record<string,unknown>)};const projectRecords=records.filter(record=>record.projectId===project.id);const scope=projectRecords.filter(record=>record.toolKey==="risk");const solicitations=projectRecords.filter(record=>record.toolKey==="solicitations");const proposals=projectRecords.filter(record=>record.toolKey==="proposal-designer");
  const packages=solicitations.length?solicitations.map((record,index)=>{const payload=record.payload as {title?:string;sent?:number;received?:number};return {title:payload.title??`Bid package ${index+1}`,sent:Number(payload.sent??8),received:Number(payload.received??(record.state==="issued"?3:0))};}):samplePackages;
  return <div className="project-shell"><aside className="project-tools"><div className="project-tools-title"><span>PROJECT TOOLS</span><b>{project.code}</b></div><NavLink end to={`/app/projects/${project.id}`}>Overview</NavLink>{modules.map(item=><NavLink key={item[0]} to={`/app/tools/${item[0]}?project=${project.id}`}>{item[2]}</NavLink>)}<div className="project-tools-divider"/><NavLink to={`/app/data?project=${project.id}&type=file`}>Files</NavLink><NavLink to={`/app/data?project=${project.id}&type=report`}>Reports</NavLink><NavLink to={`/app/data?project=${project.id}&type=template`}>Templates</NavLink></aside><section className="project-center">{toolSlug?<ToolPage slug={toolSlug} confirm={()=>{}}/>:<ProjectOverview project={project} scope={scope} solicitations={packages} proposals={proposals}/>}</section><ProjectInformation project={project} details={details} packages={packages}/></div>;
}

function ProjectOverview({project,scope,solicitations,proposals}:{project:ProjectRow;scope:WorkflowRow[];solicitations:{title:string;sent:number;received:number}[];proposals:WorkflowRow[]}) {
  const scopeComplete=scope.some(item=>item.state==="approved"||item.state==="closed");return <div className="project-overview"><div className="project-overview-head"><div><span className="eyebrow">PROJECT DASHBOARD</span><h2>{project.code} · {project.name}</h2></div><Link className="secondary" to="/app/projects">ALL PROJECTS</Link></div><div className="project-status-strip"><div><label>Status</label><strong className="status-value">{project.status}</strong><small>{project.phase}</small></div><div><label>Project lead</label><strong>{project.owner}</strong><small>Internal assignment</small></div><div><label>Scope review</label><strong>{scopeComplete?"Complete":"Incomplete"}</strong><small>{scope.length} review record{scope.length===1?"":"s"}</small></div></div><div className="project-action-grid"><article className={scopeComplete?"complete":"attention"}><span>SCOPE REVIEW</span><h3>{scopeComplete?"Coverage confirmed":"Review required"}</h3><p>{scopeComplete?"Approved scope coverage is on record.":"Complete requirements, gaps, and exclusions before award."}</p><Link to={`/app/tools/risk?project=${project.id}`}>{scopeComplete?"VIEW REVIEW":"START REVIEW"}</Link></article><article><span>SOLICITATIONS</span><h3>{solicitations.length} bid packages</h3><p>{solicitations.filter(item=>item.received>0).length} packages currently have bid coverage.</p><Link to={`/app/tools/solicitations?project=${project.id}`}>MANAGE PACKAGES</Link></article><article><span>PROPOSALS</span><h3>{proposals.length} project proposals</h3><p>{proposals.filter(item=>item.state==="approved"||item.state==="issued").length} approved or issued.</p><Link to={`/app/tools/proposal-designer?project=${project.id}`}>OPEN PROPOSALS</Link></article></div></div>;
}

function ProjectInformation({project,details,packages}:{project:ProjectRow;details:Record<string,unknown>;packages:{title:string;sent:number;received:number}[]}) {return <aside className="project-information"><div className="project-info-head"><span>PROJECT INFORMATION</span><b>{project.code}</b><h3>{project.name}</h3><p>{String(details.location??"Address not set")}</p></div><dl><div><dt>Owner</dt><dd>{String(details.projectOwner??"Not set")}</dd></div><div><dt>Architect</dt><dd>{String(details.architect??"Not set")}</dd></div><div><dt>Project lead</dt><dd>{project.owner}</dd></div><div className="wide"><dt>Description</dt><dd>{String(details.description??"No description")}</dd></div><div><dt>Size</dt><dd>{details.sizeSf?`${Number(details.sizeSf).toLocaleString()} SF`:"Not set"}</dd></div><div><dt>Anticipated value</dt><dd>{money(details.anticipatedValue)}</dd></div><div><dt>Estimated value</dt><dd>{money(details.estimatedValue)}</dd></div><div><dt>Proposed value</dt><dd>{money(details.proposedValue)}</dd></div></dl><div className="project-dates"><span>PROJECT DATES</span><div><label>Start</label><b>{project.startDate??"Not set"}</b></div><div><label>Bid / due</label><b>{project.dueDate??"Not set"}</b></div><div><label>Completion</label><b>{project.completionDate??"Not set"}</b></div></div><div className="package-list"><span>OPEN BID PACKAGES</span>{packages.map(item=>{const coverage=item.received>0,ratio=item.sent?Math.min(100,Math.round(item.received/item.sent*100)):0;return <div className={`package-row ${coverage?"covered":"uncovered"}`} key={item.title}><div><b>{item.title}</b><small>{item.received} received / {item.sent} sent</small></div><div className="coverage-bar"><i style={{width:`${ratio}%`}}/></div></div>;})}</div></aside>}
