import { useState } from "react";
import { Link, useFetcher, useLoaderData, useLocation } from "react-router";
import { modules } from "../lib/navigation";

type ToolDefinition={steps:string[];metrics:[string,string,string][];columns:string[];rows:string[][];aside:[string,string][];primary:string};
const toolDefinitions:Record<string,ToolDefinition>={
  "proposal-designer":{steps:["Choose template","Compose blocks","Review values","Publish"],metrics:[["Draft proposals","4","2 due this week"],["Approved blocks","38","6 categories"],["Reviews","3","1 assigned to you"]],columns:["Proposal","Template","Stage","Due","Owner"],rows:[["Oakfield Trails Base Bid","GC Standard","Block editing","Aug 12","R. Green"],["JHACH GMP Narrative","Healthcare","Review","Aug 11","M. Carter"],["PHSC Qualifications","Public works","Draft","Aug 21","R. Green"]],aside:[["Template library","12 approved templates"],["Recent blocks","General conditions · Alternates"],["Output formats","DOCX · PDF · editable"]],primary:"NEW PROPOSAL"},
  "project-intelligence":{steps:["Initiate","Organize","Monitor","Forecast"],metrics:[["Active projects","12","3 priority"],["Milestones","27","8 this week"],["Forecast alerts","5","2 critical"]],columns:["Project","Phase","Progress","Budget signal","Next milestone"],rows:[["Oakfield Trails","Preconstruction","72%","On plan","Scope lock"],["JHACH Pharmacy","Final pricing","88%","Watch","GMP review"],["PHSC Repairs","Scope review","46%","On plan","Trade coverage"]],aside:[["Portfolio pulse","82% milestones on time"],["Recent files","7 linked references"],["Smart forecast","2 dates need attention"]],primary:"INITIATE PROJECT"},
  subcontractors:{steps:["Discover","Qualify","Invite","Evaluate"],metrics:[["Trade partners","486","31 active trades"],["Prequals due","18","7 overdue"],["License alerts","6","FL DBPR review"]],columns:["Trade partner","Primary trade","Prequal","Bid rate","Performance"],rows:[["Apex Electrical","Electrical","Current","76%","4.7 / 5"],["Suncoast Mechanical","HVAC","Review due","64%","4.4 / 5"],["Gulf Coast Interiors","Drywall","Current","81%","4.8 / 5"]],aside:[["Data hygiene","9 merge suggestions"],["QR intake","Networking form ready"],["External checks","DBPR · FL licenses"]],primary:"ADD TRADE PARTNER"},
  solicitations:{steps:["Build scopes","Select bidders","Issue","Collect bids","Level"],metrics:[["Open solicitations","38","14 due this week"],["Invitations","264","71% viewed"],["Bids received","96","36% response"]],columns:["Scope package","Project","Invited","Received","Due"],rows:[["09 29 00 Gypsum Board","Oakfield Trails","12","5","Aug 12"],["26 00 00 Electrical","JHACH Pharmacy","9","4","Aug 11"],["07 50 00 Roofing","PHSC Repairs","7","3","Aug 21"]],aside:[["Plan room","3 active rooms"],["Addenda","2 acknowledgments due"],["Communications","18 queued reminders"]],primary:"NEW SOLICITATION"},
  rfis:{steps:["Receive","Classify","Answer","Publish","Export"],metrics:[["Open RFIs","17","6 need response"],["Draft answers","4","2 assigned to you"],["Published","63","Across 8 scopes"]],columns:["RFI","Question","Scope","Status","Age"],rows:[["PR-RFI-014","Wall type at corridor 2","Drywall","Draft answer","2d"],["PR-RFI-013","Panel schedule conflict","Electrical","Owner review","3d"],["PR-RFI-012","Roof drain elevation","Plumbing","Published","5d"]],aside:[["Owner transfer","3 ready to send"],["Trade visibility","Scope-filtered plan room"],["Exports","PDF log · transmittal"]],primary:"NEW RFI"},
  contracts:{steps:["Select template","Build scope","Review terms","Redline","Execute"],metrics:[["Draft commitments","7","$3.8M value"],["Redlines","4","2 awaiting response"],["Ready to execute","3","Scope confirmed"]],columns:["Commitment","Trade partner","Template","Stage","Value"],rows:[["Electrical subcontract","Apex Electrical","Standard subcontract","Redline","$842,000"],["HVAC subcontract","Suncoast Mechanical","Healthcare","Internal review","$1,240,000"],["Drywall subcontract","Gulf Coast Interiors","Standard subcontract","Scope build","$611,000"]],aside:[["Approved clauses","86 standard blocks"],["Scope suggestions","5 pending approval"],["Project data","12 mapped fields"]],primary:"NEW COMMITMENT"},
  risk:{steps:["Import requirements","Compare scope","Resolve gaps","Approve"],metrics:[["Requirements","124","91% covered"],["Open gaps","11","3 high risk"],["Exclusions","18","6 need review"]],columns:["Requirement","Commitment","Coverage","Risk","Owner"],rows:[["Temporary power","Electrical subcontract","Partial","High","R. Green"],["Firestopping","Drywall subcontract","Covered","Low","M. Carter"],["Controls integration","HVAC subcontract","Review","Medium","A. Foster"]],aside:[["Risk index","72 · watch"],["Scope conflicts","4 cross-trade items"],["Guardrail","Approval required"]],primary:"RUN COMPARISON"},
  submittals:{steps:["Generate log","Assign","Collect","Review","Transmit"],metrics:[["Required","142","Across 11 trades"],["Due soon","19","7 critical"],["Received","68","48% complete"]],columns:["Submittal","Spec","Trade partner","Status","Required date"],rows:[["Product data — AHU-1","23 73 00","Suncoast Mechanical","Received","Aug 18"],["Panelboards","26 24 16","Apex Electrical","Due soon","Aug 15"],["Gypsum assemblies","09 29 00","Gulf Coast Interiors","Requested","Aug 22"]],aside:[["Historical library","384 indexed submittals"],["Cover sheets","Standard markup ready"],["Destinations","Procore · Newforma · Email"]],primary:"BUILD SUBMITTAL LOG"},
  procurement:{steps:["Identify","Confirm","Track","Escalate","Deliver"],metrics:[["Critical items","23","8 confirmed"],["At risk","5","2 schedule impacts"],["Due this month","14","6 unconfirmed"]],columns:["Item","Project","Vendor","Status","Need on site"],rows:[["Main switchgear","Oakfield Trails","Apex Electrical","At risk","Mar 12, 2027"],["Air handling units","JHACH Pharmacy","Suncoast Mechanical","Confirmed","Jan 18, 2027"],["Roof insulation","PHSC Repairs","TBD","Tracking","Oct 02, 2026"]],aside:[["Schedule links","18 activities linked"],["Communications","11 email updates"],["Reminders","6 due this week"]],primary:"ADD CRITICAL ITEM"},
  schedule:{steps:["Import scope","Build activities","Set durations","Sequence","Export"],metrics:[["Activities","184","12 generated today"],["Logic checks","7","3 conflicts"],["Milestones","22","4 critical"]],columns:["Activity","Scope","Duration","Predecessor","Status"],rows:[["Frame level 2","Carpentry","10 days","Foundations","Generated"],["Rough-in level 1","MEP","18 days","Frame level 1","Review"],["Drywall level 1","Drywall","12 days","MEP rough-in","Generated"]],aside:[["Production rates","42 saved rates"],["Imports","Microsoft Project"],["Exports","MPP · polished PDF"]],primary:"GENERATE SCHEDULE"},
  closeout:{steps:["Define requirements","Request","Collect","Review","Package"],metrics:[["Requirements","96","Across 14 trades"],["Received","61","64% complete"],["Overdue","9","4 critical"]],columns:["Requirement","Trade partner","Type","Status","Due"],rows:[["O&M manuals","Suncoast Mechanical","Document","Received","May 04"],["Panel warranty","Apex Electrical","Warranty","Requested","May 10"],["As-built drawings","Gulf Coast Interiors","Drawing","Overdue","May 01"]],aside:[["File bins","Provider-linked references"],["Combined packages","3 ready to generate"],["Destinations","Procore · SharePoint"]],primary:"BUILD CLOSEOUT LOG"},
  "change-risk":{steps:["Capture event","Assess exposure","Plan action","Monitor","Close"],metrics:[["Open events","14","$486K exposure"],["High risk","3","Action required"],["Mitigated","22","$311K avoided"]],columns:["Event","Project","Exposure","Risk score","Next action"],rows:[["Steel escalation","Oakfield Trails","$142,000","82","Lock pricing"],["Design revision 07","JHACH Pharmacy","$86,000","67","Owner notice"],["Unknown utilities","PHSC Repairs","$41,000","54","Verify survey"]],aside:[["Portfolio risk","68 · elevated"],["Guardrails","No autonomous commitments"],["Recommended actions","5 awaiting approval"]],primary:"LOG CHANGE EVENT"},
};

type WorkflowRow={id:string;projectId?:string|null;toolKey:string;type:string;state:string;revision:number;payload:unknown};
export function ToolPage({slug,confirm}:{slug:string;confirm:(value:string)=>void}) {
  const module=modules.find(item=>item[0]===slug)??modules[0]; const definition=toolDefinitions[slug]??toolDefinitions["proposal-designer"];
  const {records}=useLoaderData<{records:WorkflowRow[]}>();const location=useLocation();const params=new URLSearchParams(location.search),projectId=params.get("project");const fetcher=useFetcher();const [creating,setCreating]=useState(params.get("create")==="1");const [title,setTitle]=useState("");const [detail,setDetail]=useState("");const [filter,setFilter]=useState("");const toolRecords=records.filter(record=>record.toolKey===slug&&(!projectId||!record.projectId||record.projectId===projectId)&&JSON.stringify(record.payload).toLowerCase().includes(filter.toLowerCase()));const type=slug==="proposal-designer"?"proposal":slug==="subcontractors"?"contractor":slug==="solicitations"?"solicitation":slug==="risk"?"scope-review":"workflow-item";
  function create(event:React.FormEvent){event.preventDefault();fetcher.submit({intent:"workflow-create",toolKey:slug,type,title,detail,projectId:projectId??""},{method:"post"});setTitle("");setDetail("");setCreating(false);}
  if(!projectId)return <div className="empty-state"><b>Open a project first</b><span>{module[2]} is a project-scoped workflow.</span><Link className="primary" to="/app/projects">SELECT PROJECT</Link></div>;
  return <div className="tool-workspace">
    <div className="workflow-steps">{definition.steps.map((step,index)=><div className={`workflow-step ${index===0?"active":""}`} key={step}><span>{String(index+1).padStart(2,"0")}</span>{step}</div>)}</div>
    <div className="metrics compact">{definition.metrics.map(metric=><div className="metric" key={metric[0]}><label>{metric[0]}</label><strong>{metric[1]}</strong><small>{metric[2]}</small></div>)}</div>
    <div className="tool-layout"><section className="panel"><div className="panel-head"><div><h2>{module[2]} working set</h2><span className="panel-caption">{module[3]}</span></div><div className="page-actions"><input className="tool-filter" value={filter} onChange={event=>setFilter(event.target.value)} placeholder="FILTER RECORDS"/><button className="primary" onClick={()=>setCreating(true)}>{definition.primary}</button></div></div>{creating&&<form className="inline-editor" onSubmit={create}><input autoFocus value={title} onChange={event=>setTitle(event.target.value)} placeholder={`${type} name`} required/><textarea value={detail} onChange={event=>setDetail(event.target.value)} placeholder="Scope, notes, recipients, or block content"/><div className="page-actions"><button type="button" className="secondary" onClick={()=>setCreating(false)}>CANCEL</button><button className="primary">SAVE DRAFT</button></div></form>}<div className="table-wrap"><table className="data-table"><thead><tr><th>Record</th><th>Type</th><th>Status</th><th>Revision</th><th>Actions</th></tr></thead><tbody>{toolRecords.map(record=>{const payload=record.payload as {title?:string;detail?:string};return <tr key={record.id}><td><b>{payload?.title??"Untitled"}</b><span className="row-detail">{payload?.detail}</span></td><td className="status-value">{record.type}</td><td><select className="cell-select status-value" value={record.state} onChange={event=>fetcher.submit({intent:"workflow-update",id:record.id,state:event.target.value,title:payload?.title??"Untitled",detail:payload?.detail??""},{method:"post"})}>{["draft","review","approved","issued","closed"].map(state=><option key={state}>{state}</option>)}</select></td><td>{record.revision}</td><td><button className="danger-button" onClick={()=>{if(window.confirm("Delete this record?"))fetcher.submit({intent:"workflow-delete",id:record.id},{method:"post"});}}>DELETE</button></td></tr>})}{!toolRecords.length&&definition.rows.map((row,index)=><tr key={index}><td><b>{row[0]}</b></td><td>Example</td><td className="status-value">{row[2]??"Reference"}</td><td>—</td><td/></tr>)}</tbody></table></div></section>
      <aside className="tool-aside"><div className="panel-head"><h2>Workspace intelligence</h2><Link className="text-link" to={`/app/settings/tools/${slug}`}>SETUP →</Link></div>{definition.aside.map(item=><button className="insight-row" key={item[0]} onClick={()=>setCreating(true)}><b>{item[0]}</b><span>{item[1]}</span><i>→</i></button>)}</aside>
    </div>
  </div>;
}
