import { useEffect, useMemo, useRef, useState } from "react";
import { Link, NavLink, useFetcher, useLoaderData, useLocation, useNavigate } from "react-router";
import { Dashboard } from "../components/dashboard";
import { ProjectsPage } from "../components/projects-page";
import { ToolPage } from "../components/tool-page";
import { bulkUpdateProjects, createProject, createProjectsFromUpload, deleteProjects, listProjects, updateProject } from "../lib/projects.server";
import { globalLinks, modules, settingsLinks } from "../lib/navigation";
import { createFeedback, listFeedback } from "../lib/feedback.server";
import { createWorkflowRecord, deleteWorkflowRecord, getCompany, listToolConfigurations, listWorkflowRecords, setToolEnabled, updateCompanySettings, updateWorkflowRecord } from "../lib/workflows.server";
import type { Route } from "./+types/application";

export function meta(): Route.MetaDescriptors { return [{title:"GREENSIGN — Construction Intelligence"}]; }
export async function loader() { return {projects:await listProjects(),feedback:await listFeedback(),records:await listWorkflowRecords(),configurations:await listToolConfigurations(),company:await getCompany(),runtime:{version:process.env.APP_VERSION??"0.4.0",buildDate:process.env.BUILD_DATE??"Development build",environment:process.env.NODE_ENV??"development",server:"Online",database:"Connected"}}; }
export async function action({request}:Route.ActionArgs) {
  const form=await request.formData(); const intent=String(form.get("intent")??"");
  if(intent==="update") await updateProject(String(form.get("id")),String(form.get("field")),String(form.get("value")??"")||null);
  else if(intent==="bulk-update") await bulkUpdateProjects(parseIds(form.get("ids")),String(form.get("status")??"active"));
  else if(intent==="delete") await deleteProjects(parseIds(form.get("ids")));
  else if(intent==="create") await createProject();
  else if(intent==="create-from-file") {const file=form.get("projectFile");if(!(file instanceof File))throw new Response("Project file is required",{status:400});await createProjectsFromUpload(file);}
  else if(intent==="feedback") await createFeedback(String(form.get("note")??""),String(form.get("page")??""),JSON.parse(String(form.get("context")??"{}")));
  else if(intent==="workflow-create") await createWorkflowRecord(String(form.get("toolKey")),String(form.get("type")??"item"),String(form.get("projectId")??"")||null,{title:String(form.get("title")??"Untitled"),detail:String(form.get("detail")??"")});
  else if(intent==="workflow-update") await updateWorkflowRecord(String(form.get("id")),String(form.get("state")??"draft"),{title:String(form.get("title")??"Untitled"),detail:String(form.get("detail")??"")});
  else if(intent==="workflow-delete") await deleteWorkflowRecord(String(form.get("id")));
  else if(intent==="tool-toggle") await setToolEnabled(String(form.get("toolKey")),String(form.get("enabled"))==="true");
  else if(intent==="company-setting") await updateCompanySettings(String(form.get("key")),String(form.get("value")??""));
  else if(intent==="activity-approve") await createWorkflowRecord("activity","approval",null,{title:String(form.get("title")),detail:String(form.get("detail"))},"approved");
  else throw new Response("Unsupported project action",{status:400});
  return {ok:true};
}
function parseIds(value:FormDataEntryValue|null){try{const parsed=JSON.parse(String(value??"[]")); return Array.isArray(parsed)?parsed.map(String):[];}catch{return [];}}

function ConfirmDialog({title,onClose}:{title:string;onClose:()=>void}) {
  return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><div className="dialog" role="dialog" aria-modal="true" onMouseDown={event=>event.stopPropagation()}><div className="eyebrow">WORKFLOW ENDPOINT</div><h2>{title}</h2><p>This interface is ready for workflow review. Persistent behavior for this module will be implemented in its build phase.</p><div className="dialog-actions"><button className="primary" onClick={onClose}>OK</button></div></div></div>;
}

function ProjectImportDialog({onClose}:{onClose:()=>void}) {
  const fetcher=useFetcher();const [file,setFile]=useState<File>();
  function submit(event:React.FormEvent){event.preventDefault();if(!file)return;const form=new FormData();form.set("intent","create-from-file");form.set("projectFile",file);fetcher.submit(form,{method:"post",encType:"multipart/form-data"});onClose();}
  return <div className="dialog-backdrop" role="presentation" onMouseDown={onClose}><form className="dialog import-dialog" onSubmit={submit} onMouseDown={event=>event.stopPropagation()}><div className="eyebrow">NEW PROJECT</div><h2>Import project file</h2><p>Upload JSON or CSV containing project fields such as code, name, status, phase, owner, startDate, dueDate, and completionDate.</p><label className="file-drop"><input type="file" accept=".json,.csv,application/json,text/csv" onChange={event=>setFile(event.target.files?.[0])}/><b>{file?.name??"CHOOSE JSON OR CSV"}</b><span>One file may contain one or multiple projects.</span></label><div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>CANCEL</button><button className="primary" disabled={!file}>IMPORT PROJECT</button></div></form></div>;
}

function FeedbackComposer({x,y,page,onClose}:{x:number;y:number;page:string;onClose:()=>void}) {
  const fetcher=useFetcher(); const [note,setNote]=useState("");
  const position={left:Math.max(8,Math.min(x,window.innerWidth-360)),top:Math.max(8,Math.min(y,window.innerHeight-210))};
  function save(event:React.FormEvent){event.preventDefault();fetcher.submit({intent:"feedback",note,page,context:JSON.stringify({viewport:`${window.innerWidth}x${window.innerHeight}`,url:window.location.href})},{method:"post"});onClose();}
  return <form className="feedback-composer" style={position} onSubmit={save} onContextMenu={event=>event.stopPropagation()}><div className="eyebrow">FLAG FOR REVIEW</div><textarea autoFocus value={note} onChange={event=>setNote(event.target.value)} placeholder="Describe the issue or suggestion…"/><div className="feedback-meta">Page and viewport context will be attached automatically.</div><div className="dialog-actions"><button type="button" className="secondary" onClick={onClose}>CANCEL</button><button className="primary" disabled={!note.trim()}>SAVE NOTE</button></div></form>;
}

const commandRoutes:Record<string,string>={"/dashboard":"dashboard","/projects":"projects","/data":"data","/network":"network","/proposal":"tools/proposal-designer","/project-intelligence":"tools/project-intelligence","/contractors":"tools/subcontractors","/subcontractors":"tools/subcontractors","/solicitations":"tools/solicitations","/rfis":"tools/rfis","/contracts":"tools/contracts","/scope-review":"tools/risk","/risk":"tools/risk","/submittals":"tools/submittals","/procurement":"tools/procurement","/schedule":"tools/schedule","/closeout":"tools/closeout","/change-risk":"tools/change-risk","/settings":"settings/account","/account":"settings/account","/company":"settings/company","/contacts":"settings/contacts","/features":"settings/features","/connections":"settings/connections","/subscription":"settings/subscription","/feedback":"feedback"};
const commands=[...Object.keys(commandRoutes),"/new-project","/quick-add","/new-proposal","/new-contractor","/new-solicitation","/commands","/ver"];

function Settings({section,toolSlug}:{section?:string;toolSlug?:string}) {
  const fetcher=useFetcher();const data=useLoaderData<{configurations:{toolKey:string;enabled:boolean}[];company:{settings:unknown}}>();
  const tool=modules.find(item=>item[0]===toolSlug); const title=tool?`${tool[2]} setup`:settingsLinks.find(item=>item[0]===section)?.[1]??"Account info";
  const rows=tool?[["Enable tool","Make this module available in the current company environment"],["Tool setup","Define defaults, stages, ownership and workflow rules"],["Templates","Create and manage approved reusable templates"],["Field maps","Map standardized inputs and outputs between modules"],["Connectors","Configure external workflow and storage connections"],["Confirmation guardrails","Require approval before parsed data is committed"]]:settingsRows[section??"account"]??settingsRows.account;
  const companySettings=(data.company.settings??{}) as Record<string,unknown>;const enabled=toolSlug?data.configurations.find(item=>item.toolKey===toolSlug)?.enabled??false:false;
  return <div className="settings-grid"><nav className="settings-nav">{settingsLinks.map(item=><NavLink key={item[0]} to={`/app/settings/${item[0]}`}>{item[1]}</NavLink>)}<div className="settings-label">TOOL SETTINGS</div>{modules.map(item=><NavLink key={item[0]} to={`/app/settings/tools/${item[0]}`}>{item[2]}</NavLink>)}</nav><section className="settings-card"><div className="panel-head"><div><h2>{title}</h2><span className="panel-caption">Company environment configuration · changes save immediately</span></div></div>{rows.map((row,index)=>{const key=toolSlug?`${toolSlug}:${index}`:`${section??"account"}:${index}`;const saved=companySettings[key];const on=toolSlug&&index===0?enabled:saved===true||saved==="true";return <div className="setting-row" key={row[0]}><div><b>{row[0]}</b><span>{row[1]}</span></div><button className={`toggle ${on?"on":""}`} aria-pressed={on} aria-label={`Toggle ${row[0]}`} onClick={()=>toolSlug&&index===0?fetcher.submit({intent:"tool-toggle",toolKey:toolSlug,enabled:String(!on)},{method:"post"}):fetcher.submit({intent:"company-setting",key,value:String(!on)},{method:"post"})}/></div>;})}</section></div>;
}
const settingsRows:Record<string,string[][]>={
  account:[["Profile information","Name, email and personal preferences"],["Security","Password, sessions and future OAuth connections"],["Notifications","Workflow assignments and deadline alerts"],["Appearance","Environment typeface and density"]],
  company:[["Company identity","Legal name, logo and operating address"],["Environment URL","Company-specific GREENSIGN subdomain"],["Default standards","Codes, divisions and workflow conventions"],["Data policy","Retention, approvals and audit requirements"]],
  contacts:[["Company contacts","Manage internal and external contacts"],["Trades","Define and organize supported trade categories"],["Contact roles","Estimator, PM, superintendent and accounting"],["Import rules","Review and approve contact merges"]],
  features:[["Enabled modules","Control tools available in this environment"],["Feature previews","Opt into approved preview capabilities"],["User assignments","Assign module access by role"],["Environment status","Enable, suspend or disable this instance"]],
  connections:[["File providers","SharePoint, Dropbox and indexed references"],["Project systems","Procore, Newforma and Trimble"],["Accounting","Sage and supported cost imports"],["Email and calendar","Communication tracking and reminders"]],
  subscription:[["Current plan","GREENSIGN foundation workspace"],["Licensed users","Manage admin and member seats"],["Module access","Review included and optional tools"],["Billing contact","Invoices and subscription notices"]],
};

function MenuPopover({close,projectId}:{close:()=>void;projectId?:string}) {
  const preconstruction=modules.slice(0,7),operations=modules.slice(7);
  if(!projectId)return <div className="menu-popover project-required"><div className="eyebrow">PROJECT CONTEXT REQUIRED</div><h2>Open a project to use construction tools</h2><p>Project tools, records, and actions are scoped to the active project.</p><Link className="primary" onClick={close} to="/app/projects">SELECT PROJECT</Link></div>;
  const url=(slug:string)=>`/app/tools/${slug}?project=${projectId}`;
  return <div className="menu-popover"><div className="menu-section"><span>PRECONSTRUCTION</span><div className="menu-grid">{preconstruction.map(item=><Link key={item[0]} onClick={close} to={url(item[0])}><i>{item[1]}</i>{item[2]}</Link>)}</div></div><div className="menu-divider"/><div className="menu-section"><span>PROJECT OPERATIONS</span><div className="menu-grid">{operations.map(item=><Link key={item[0]} onClick={close} to={url(item[0])}><i>{item[1]}</i>{item[2]}</Link>)}</div></div></div>;
}

function AccountPopover({close}:{close:()=>void}) {return <div className="account-popover"><div className="account-heading"><b>R. GREEN</b><span>HCO Builders · Administrator</span></div>{settingsLinks.map(item=><Link key={item[0]} onClick={close} to={`/app/settings/${item[0]}`}>{item[1]}</Link>)}</div>;}

function GodMode({confirm}:{confirm:(value:string)=>void}) {const data=useLoaderData<{company:{name:string;slug:string;status:string};configurations:{enabled:boolean}[];records:unknown[];feedback:unknown[]}>();const cards=[["Company environment",`${data.company.name} · ${data.company.status}`],["Module assignments",`${data.configurations.filter(item=>item.enabled).length} enabled tools`],["Workflow records",`${data.records.length} persistent records`],["Instance domain",`${data.company.slug}.greensign.app`],["Feature flags","Company and tool controls connected"],["Feedback audit",`${data.feedback.length} captured items`]];return <div className="module-grid">{cards.map(item=><article className="module-card" key={item[0]}><span className="number">PRIVATE CONTROL</span><h3>{item[0]}</h3><p>{item[1]}</p><button className="secondary" onClick={()=>confirm(`Manage ${item[0]}`)}>MANAGE</button></article>)}</div>;}

export default function Application({loaderData}:Route.ComponentProps) {
  const location=useLocation(),navigate=useNavigate(),commandRef=useRef<HTMLInputElement>(null); const base=location.pathname.startsWith("/mockup")?"/mockup":"/app"; const path=location.pathname.replace(/^\/(?:app|mockup)\/?/,"").split("/").filter(Boolean); const [menuOpen,setMenuOpen]=useState(false); const [accountOpen,setAccountOpen]=useState(false); const [dialog,setDialog]=useState<string>(); const [importOpen,setImportOpen]=useState(false); const [command,setCommand]=useState(""); const [commandActive,setCommandActive]=useState(false); const [commandTip,setCommandTip]=useState<string>(); const [feedbackPoint,setFeedbackPoint]=useState<{x:number;y:number}>(); const [godMode,setGodMode]=useState(false);
  const current=path[0]||"dashboard",toolSlug=current==="tools"?path[1]:undefined,settingsSection=current==="settings"?path[1]:undefined,settingsTool=settingsSection==="tools"?path[2]:undefined;const activeProjectId=current==="projects"&&path[1]?path[1]:new URLSearchParams(location.search).get("project")??undefined;
  const title=useMemo(()=>godMode?"Environment Control":toolSlug?modules.find(item=>item[0]===toolSlug)?.[2]:current==="settings"?(settingsTool?`${modules.find(item=>item[0]===settingsTool)?.[2]} setup`:"Settings"):globalLinks.find(item=>item[0]===current)?.[1]??"Workspace",[current,toolSlug,settingsTool,godMode]);
  useEffect(()=>{function shortcut(event:KeyboardEvent){const target=event.target as HTMLElement;if(event.key==="/"&&!target.matches("input,textarea,select")){event.preventDefault();setCommand("/");setCommandActive(true);requestAnimationFrame(()=>commandRef.current?.focus());}if(event.key==="Escape"&&document.activeElement===commandRef.current){commandRef.current?.blur();setCommand("");setCommandActive(false);setCommandTip(undefined);}}window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut);},[]);
  useEffect(()=>{if(!commandTip)return;const timer=window.setTimeout(()=>setCommandTip(undefined),5000);return()=>window.clearTimeout(timer);},[commandTip]);
  useEffect(()=>{function capture(event:MouseEvent){const target=event.target as HTMLElement;if(target.closest("input,textarea,select,[contenteditable=true]"))return;event.preventDefault();setFeedbackPoint({x:event.clientX,y:event.clientY});}window.addEventListener("contextmenu",capture);return()=>window.removeEventListener("contextmenu",capture);},[]);
  function closeMenus(){setMenuOpen(false);setAccountOpen(false);}
  function resetCommand(){setCommand("");setCommandActive(false);commandRef.current?.blur();}
  function runCommand(event:React.FormEvent){event.preventDefault();const value=command.trim(),normalized=value.toLowerCase();if(value==="/gm_RH"){setGodMode(true);resetCommand();return;}const query=normalized.match(/(?:go to|open|show)(?: project)?\s+([a-z0-9-]+)/i)?.[1];const project=query&&loaderData.projects.find(item=>item.code.toLowerCase()===query||item.name.toLowerCase().includes(query));if(project){navigate(`${base}/projects/${project.id}`);resetCommand();return;}const route=commandRoutes[normalized];if(route){if(route.startsWith("tools/")&&!activeProjectId){setCommandTip("Open a project before using project tools.");resetCommand();return;}navigate(`${base}/${route}${route.startsWith("tools/")?`?project=${activeProjectId}`:""}`);setGodMode(false);resetCommand();return;}if(normalized==="/commands"){setCommandTip(`Commands: ${commands.join(", ")}. You can also type “go to 26-020”.`);resetCommand();return;}if(normalized==="/ver"){const runtime=loaderData.runtime;setCommandTip(`GREENSIGN ${runtime.version}\nBuild: ${runtime.buildDate}\nServer: ${runtime.server} · Database: ${runtime.database}\nEnvironment: ${runtime.environment}\nRoute: ${location.pathname} · Viewport: ${window.innerWidth}×${window.innerHeight}`);resetCommand();return;}if(normalized==="/new-project"){setImportOpen(true);resetCommand();return;}const actions:Record<string,string>={"/quick-add":"Quick add","/new-proposal":"New proposal","/new-contractor":"New contractor","/new-solicitation":"New solicitation"};if(actions[normalized]){if(!activeProjectId&&normalized!=="/quick-add"){setCommandTip("Open a project before starting this workflow.");resetCommand();return;}setDialog(actions[normalized]);resetCommand();return;}setCommandTip(value?`Command not recognized: ${value}. Try /commands.`:"Type a command to continue");}
  const subtitle=current==="projects"?"Filter, edit and manage the company project portfolio.":godMode?"Manage environments, accounts, modules and tenant availability.":toolSlug?modules.find(item=>item[0]===toolSlug)?.[3]:"Connected construction intelligence with confirmation-first workflows.";
  return <div className="app-shell"><header className="topbar"><div className="top-left"><button className={`menu-button ${menuOpen?"active":""}`} onClick={()=>{setMenuOpen(value=>!value);setAccountOpen(false);}} aria-label="Open tool menu">☰</button><Link className="brand" to="/app/dashboard" onClick={closeMenus}><i className="mark"/><span>GREENSIGN</span></Link><nav className="global-nav">{globalLinks.map(item=><NavLink key={item[0]} to={`/app/${item[0]}`} onClick={closeMenus}>{item[1]}</NavLink>)}</nav>{menuOpen&&<MenuPopover close={closeMenus} projectId={activeProjectId}/>}</div><div className="top-actions"><button className="quick-add" onClick={()=>setDialog("Quick add")}>＋ QUICK ADD</button><button className="avatar" onClick={()=>{setAccountOpen(value=>!value);setMenuOpen(false);}}>RG</button>{accountOpen&&<AccountPopover close={closeMenus}/>}</div></header>
    <main className={`main ${godMode?"god":""}`}><div className="project-bar"><div><span>ACTIVE ENVIRONMENT</span><b>HCO BUILDERS</b></div><div className="crumb">GREENSIGN / <b>{title}</b></div></div><div className="page-head"><div><div className="eyebrow">{godMode?"PRIVATE SUPERUSER SESSION":toolSlug?"CONSTRUCTION TOOL":current==="settings"?"ENVIRONMENT SETTINGS":"OPERATING WORKSPACE"}</div><h1>{title}</h1><div className="subtitle">{subtitle}</div></div><div className="page-actions">{toolSlug&&<Link className="tool-settings" to={`/app/settings/tools/${toolSlug}`}>⚙ TOOL SETUP</Link>}{current==="dashboard"?<button className="primary" onClick={()=>setImportOpen(true)}>+ NEW</button>:current!=="projects"&&<button className="primary" onClick={()=>setDialog(`New ${title}`)}>+ NEW</button>}</div></div>
      {godMode?<GodMode confirm={setDialog}/>:current==="dashboard"?<Dashboard confirm={setDialog}/>:current==="projects"?<ProjectsPage projects={loaderData.projects}/>:current==="settings"?<Settings section={settingsSection} toolSlug={settingsTool}/>:toolSlug?<ToolPage slug={toolSlug} confirm={setDialog}/>:current==="data"||current==="network"?<div className="empty-state"><b>{title} workspace</b><span>The endpoint is ready for its functional build phase.</span><button className="primary" onClick={()=>setDialog(`Open ${title} workflow`)}>OK</button></div>:<Dashboard confirm={setDialog}/>}</main>
    <form className={`commandbar ${commandActive?"active":""}`} onSubmit={runCommand}><span className="slash">/</span><input ref={commandRef} list="command-options" value={command} onFocus={()=>setCommandActive(true)} onBlur={()=>setCommandActive(false)} onChange={event=>setCommand(event.target.value)} placeholder="Type /commands or ask to go to a project…" aria-label="Global command"/><datalist id="command-options">{commands.map(item=><option value={item} key={item}/>)}</datalist><button type="submit" className="command-run">RUN</button><small>GLOBAL COMMAND</small>{commandTip&&<div className="command-tooltip" role="status">{commandTip}</div>}</form>{feedbackPoint&&<FeedbackComposer x={feedbackPoint.x} y={feedbackPoint.y} page={location.pathname} onClose={()=>setFeedbackPoint(undefined)}/>} {importOpen&&<ProjectImportDialog onClose={()=>setImportOpen(false)}/>} {dialog&&<ConfirmDialog title={dialog} onClose={()=>setDialog(undefined)}/>}</div>;
}
